title: Project
num: date
icon: 📘

status:
  draft:
    label: Draft
    text: The project is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The project is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The project is online and listed in the blog

columns:
  main:
    width: 2/3
    fields:
      subheading:
        label: Subheading
        type: text
        validate: notEmpty
        required: true
      cover:
        label: Cover image
        type: files
        multiple: false
        layout: cards
        size: large
        uploads:
          template: image
        validate: notEmpty
        required: true
      website:
        label: Website
        description: Link to project site for iframe / embedding
        type: url
      description:
        label: Short description
        type: textarea
      participate:
        label: Paths to participating
        type: textarea
        when:
          seeking_participants: true
        required: true
      meetings:
        type: textarea
        label: Meetings

  sidebar:
    width: 1/3
    sections:
      ## add in to allow switching pages
      bouncernav:
        type: bouncernav
      meta:
        type: fields
        fields:
          category:
            type: tags
            options:
              type: query
              query: site.find('projects').children.pluck("category", ",", true)
          date:
            type: date
            time: false
            default: now
          project_status:
            label: Project status
            type: tags
            options:
              - "Active"
              - "Complete"
              - "Paused"
              - "Pending Funding"
              - "Inactive"
          seeking_participants:
            label: Seeking participants
            type: toggle
            text:
              - "No"
              - "Yes"
          links:
            type: structure
            fields:
              text:
                label: Text
                type: text
              url:
                label: URL
                type: url
          type:
            type: tags
            options:
              - "Tool"
              - "Publication"
              - "Community of Practice"
              - "Cross-group Collaboration"
              - "Fundraising"
              - "Guidebook"
              - "Data Set"
              - "Coordination Tool"
              - "Roundtable"
              - "R&D"
              - "Market Intervention"
              - "Data Standards"
              - "Technical Standard"
          research_directors:
            label: Research Directors
            type: users
            query: kirby.users ## Allow selecting anyone (Member, Editor, or Admin)
          members:
            label: Contributors
            type: pages
            query: site.find('people').children
          contact:
            type: email
      pages:
        type: pages
        template: default