title: Dashboard

tabs:
  content:
    icon: document
    columns:
      - width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - page
              - home
              - projects
              - people
              - deliberative-tool-gallery
      - width: 1/2
        sections:
          projects: sections/projects
  settings:
    label: Site settings
    icon: cog
    columns:
      - width: 1/2
        fields:
          info:
            label:
            type: info
            text: ℹ️ Site wide SEO settings, these maybe be overwritted on individual pages by titles, subheading and cover images.
          seoTitle:
            label: SEO title
            type: text
            required: true
          seoDescription:
            label: SEO description
            type: textarea
            buttons: false
            required: true
          seoImage:
            label: SEO Image
            type: files
            multiple: false
            layout: cards
            size: large
            required: true
      - width: 1/2
        fields:
          mainMenu:
            type: structure
            label: Main menu pages
            help: Toggle seperator to true to add seperator below menu item.
            required: true
            fields:
              page:
                type: pages
                multiple: false
                required: true
              seperator:
                type: toggle
                help: Toggle seperator to true/yes to add seperator below menu item.
                text:
                  - "No"
                  - "Yes"
      - width: 1/2
        fields:
          avatar:
            extends: sections/image
            label: Avatar
            help: Default image used for when person does not provide image
            max: 1
            required: true
            image:
              ratio: 1/1
              cover: true
  redirects:
    icon: shuffle
    sections:
      extends: plugin-redirects3xx
